// Deterministic emitter (ADR-0007): the sole writer of a Course. Takes an already-
// validated CourseSpec and writes it as a LIBRARY entry under courses/<slug>/
// (CURRICULUM.md + modules/<n>.<slug>/ + course.yml + bundled progress templates).
// It does NOT touch root — courses.selectCourse() mirrors an entry to root when it
// becomes active. M1: sandbox is always null.
import { cp, mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { resolveInRepo } from "../files.ts";
import { slugify, PROGRESS_TEMPLATES } from "../courses.ts";
import type { CourseSpec, ModuleSpec } from "./schema.ts";

export interface EmitResult {
  ok: boolean;
  slug?: string;
  modules: number;
  error?: string;
}

/** Render CURRICULUM.md's module table (parsed by content.ts ROW_RE). */
function curriculumMarkdown(spec: CourseSpec): string {
  const rows = spec.modules
    .map((m) => `| ${m.number} | ${m.title} | \`${m.slug}\` | ${m.principle} | 🟢 |`)
    .join("\n");
  return [
    `# ${spec.label}`,
    "",
    "> Generated by the Praxis Generator. Each row is one Module.",
    "",
    "| # | Module | `slug` | Core principle | Status |",
    "| - | ------ | ------ | -------------- | ------ |",
    rows,
    "",
  ].join("\n");
}

/** Lesson body + the emitter-guaranteed "## 🧠 Active recall" section. */
function lessonMarkdown(m: ModuleSpec): string {
  const recall = m.recall.map((q, i) => `${i + 1}. ${q}`).join("\n");
  return `${m.lesson.trim()}\n\n## 🧠 Active recall\n\n${recall}\n`;
}

/** Per-Course manifest: archetypes now; Floor-check commands land in M2. */
function courseYaml(spec: CourseSpec): string {
  const lines = [`label: ${JSON.stringify(spec.label)}`, "modules:"];
  for (const m of spec.modules) {
    lines.push(`  - slug: ${m.slug}`);
    lines.push(`    archetype: ${m.archetype}`);
  }
  lines.push("sandbox: null");
  return `${lines.join("\n")}\n`;
}

export async function emitCourse(spec: CourseSpec): Promise<EmitResult> {
  // Defense in depth beyond zod: every Module must teach and must gate on Recall.
  for (const m of spec.modules) {
    if (!m.lesson.trim()) return { ok: false, modules: 0, error: `module ${m.slug} has an empty lesson` };
    if (m.recall.length === 0) return { ok: false, modules: 0, error: `module ${m.slug} has no recall` };
  }

  const slug = await slugify(spec.label);
  const dir = resolveInRepo(`courses/${slug}`);

  try {
    await mkdir(dir, { recursive: true });
    await writeFile(path.join(dir, "CURRICULUM.md"), curriculumMarkdown(spec), "utf8");
    for (const m of spec.modules) {
      const mdir = path.join(dir, "modules", `${m.number}.${m.slug}`);
      await mkdir(mdir, { recursive: true });
      await writeFile(path.join(mdir, "lesson.md"), lessonMarkdown(m), "utf8");
      if (m.challenge?.trim()) {
        await writeFile(path.join(mdir, "challenge.md"), `${m.challenge.trim()}\n`, "utf8");
      }
    }
    await writeFile(path.join(dir, "course.yml"), courseYaml(spec), "utf8");

    // Bundle the progress templates so a mirrored course has its own learner-state seeds.
    const progDir = path.join(dir, "progress");
    await mkdir(progDir, { recursive: true });
    for (const t of PROGRESS_TEMPLATES) {
      const src = resolveInRepo(`progress/${t}`);
      if (existsSync(src)) await cp(src, path.join(progDir, t));
    }
  } catch (e) {
    return { ok: false, modules: 0, error: `emit failed: ${(e as Error).message}` };
  }

  return { ok: true, slug, modules: spec.modules.length };
}
